'use client'
import { CssBaseline, ThemeProvider} from '@mui/material';
import "./globals.css";
import NavBar from "@/components/Navbar";
import theme from './theme';


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
        <body style={{marginLeft:"5%", marginRight:"5%"}}>
        <ThemeProvider theme={theme}>
            <CssBaseline />
            <NavBar/>
            <main style={{marginTop:"10%"}}>
                {children}
            </main>
        </ThemeProvider>
        </body>
        </html>
    );
}
